[package]
name = "authentication"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2rs = "0.2.5"
dotenv = "0.15.0"
rand = "0.8.5"
rusqlite = "0.29.0"
