[package]
name = "tui-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
itertools = "0.11.0"
ratatui = "0.23.0"
time = "0.3.28"
tui = "0.19.0"
